{% set name = "xeus-python" %}
{% set version = "0.0.3" %}
{% set sha256 = "c8e3304304d32bb9f4e209e43fa5665236b16b0494184215791ca113f66dc2b4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/QuantStack/xeus-python/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - toolchain
    - cmake
    - cppzmq 4.3.0
    - zeromq 4.2.5
    - gcc-7             # [linux]
    - xtl >=0.5.0,<0.6
    - xeus >=0.17.0,<0.18.0
    - pybind11 >=2.2.4,<3.0
    - nlohmann_json >=3.3.0,<4.0
    - python
  run:
    - zeromq 4.2.5
    - xeus >=0.17.0,<0.18.0
    - jedi >=0.13.1,<0.14
    - python

test:
  commands:
    - test -f ${PREFIX}/bin/xeus-python                                                                    # [unix]
    - test -f ${PREFIX}/share/jupyter/kernels/xeus-python/kernel.json                                      # [unix]
    - if exist %LIBRARY_BIN%\\xeus-python.exe (exit 0) else (exit 1)                                       # [win]
    - if exist %LIBRARY_PREFIX%\\share\\jupyter\\kernels\\xeus-python\\kernel.json (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xeus-python
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Jupyter kernel for the Python programming language based on xeus'
  description: 'xeus-python is a Jupyter kernel for Python based on the native implementation of the Jupyter protocol xeus.'
  doc_url: http://xeus-python.readthedocs.io
  dev_url: https://github.com/QuantStack/xeus-python

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - martinRenou
